### ISSUE TITLE
Adding list via xml

### ISSUE THREAD

**Issue by veebiajakiriperfection** [PigeonPack/pigeon-pack#5]
Hello!

1. Can you please help me with a question. Is it possible to add lists to PogeonPack with xml file (Exel) ? And if then how?
2. Is there a limit for e-mails to send. For example if my campaign should go to 50 000 people, is it possible to do or there are limits for that?

**Comment by lewayotte** [comment]
Hello.

1) I don't have any import scripts yet.
2) There are no limits built into the plugin, the only limit you'd have would be with your mail provider.

Thanks!
